# Generated by Django 3.1.7 on 2021-03-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(default='user_default.png', upload_to='fotos_perfil'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_camas', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_cama', models.TextField(blank=True, max_length=255, null=True)),
                ('accesorios', models.TextField(blank=True, max_length=255, null=True)),
                ('precio', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_habitacion', models.ImageField(upload_to='fotos_habitacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='alojamiento.estate')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='alojamiento.place')),
            ],
        ),
    ]
