# Generated by Django 3.1.7 on 2021-03-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0004_profile_cantidad_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cama', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='tipo_cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='alojamiento.type'),
        ),
    ]
