# Generated by Django 3.1.7 on 2021-03-28 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0006_auto_20210328_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
