# Generated by Django 3.1.7 on 2021-03-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0007_room_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='numero_habitacion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('rut', models.CharField(blank=True, max_length=9, null=True)),
                ('foto_empleado', models.ImageField(upload_to='fotos_empleados_empresas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamiento.profile')),
            ],
        ),
    ]
