# Generated by Django 3.1.7 on 2021-03-31 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0011_auto_20210330_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='cantidad_camas',
        ),
        migrations.RemoveField(
            model_name='room',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='room',
            name='huesped',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='huespedes', to='alojamiento.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='alojamiento.employee'),
        ),
        migrations.AlterField(
            model_name='room',
            name='numero_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='alojamiento.number'),
        ),
    ]
