# Generated by Django 3.1.7 on 2021-03-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0012_auto_20210330_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sede',
        ),
    ]
