# Generated by Django 3.1.7 on 2021-03-31 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0013_remove_room_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='alojamiento.room')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_name', to='alojamiento.employee')),
            ],
        ),
    ]
