# Generated by Django 3.1.7 on 2021-03-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0014_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='huesped',
        ),
    ]
