# Generated by Django 3.1.7 on 2021-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0016_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='texto',
        ),
        migrations.AddField(
            model_name='post',
            name='Titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
