# Generated by Django 3.1.7 on 2021-04-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0017_auto_20210331_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='foto_empleado',
        ),
    ]
