# Generated by Django 3.1.7 on 2021-04-03 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamiento', '0019_auto_20210403_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_client',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Revision', 'En Revision'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking_client',
            name='tipo_habitacion',
            field=models.CharField(blank=True, choices=[('Básico', 'Básico'), ('Plus', 'Plus'), ('Premuim', 'Premuim')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tipo_habitacion',
            field=models.CharField(blank=True, choices=[('Básico', 'Básico'), ('Plus', 'Plus'), ('Premuim', 'Premuim')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_habitacion', models.CharField(blank=True, choices=[('Básico', 'Básico'), ('Plus', 'Plus'), ('Premuim', 'Premuim')], max_length=50, null=True)),
                ('precio_servivio', models.CharField(blank=True, max_length=50, null=True)),
                ('noches', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True)),
                ('precio_noches', models.CharField(blank=True, max_length=50, null=True)),
                ('personas', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True)),
                ('precio_personas', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('from_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
