# Generated by Django 3.1.7 on 2021-04-04 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamiento', '0020_auto_20210403_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_client',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking_client',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Revision', 'En Revision'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='En Revision', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking_client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
