# Generated by Django 3.1.7 on 2021-04-04 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0021_auto_20210404_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_client',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
