# Generated by Django 3.1.7 on 2021-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0022_auto_20210404_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='estado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Mantenimiento', 'En Mantenimiento')], max_length=50, null=True),
        ),
    ]
