# Generated by Django 3.1.7 on 2021-04-05 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0023_auto_20210404_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='precio_servivio',
            new_name='precio_servivcio',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
