# Generated by Django 3.1.7 on 2021-04-06 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamiento', '0025_ticket_fecha_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='estado_huesped',
            field=models.CharField(blank=True, choices=[('En Alojamiento', 'En Alojamiento'), ('Retirado', 'Retirado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='from_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
