# Generated by Django 3.1.7 on 2021-04-06 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0026_auto_20210405_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
