# Generated by Django 3.1.7 on 2021-04-07 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamiento', '0028_auto_20210406_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('rubro', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guest',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='alojamiento.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='estado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('En Mantenimiento', 'En Mantenimiento')], max_length=50, null=True),
        ),
    ]
