# Generated by Django 3.1.7 on 2021-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0029_auto_20210406_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='telefono',
        ),
        migrations.AddField(
            model_name='employee',
            name='solicitante',
            field=models.CharField(blank=True, choices=[('Solicitante', 'Solicitante'), ('No Solicitante ', 'No Solicitante')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proovider',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
