# Generated by Django 3.1.7 on 2021-04-09 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0031_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.CharField(blank=True, max_length=50, null=True)),
                ('rut_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empresa',
            new_name='empleado',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='solicitante',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Ejecutivo', 'Ejecutivo'), ('Especiales', 'Especiales'), ('Generales', 'Generales')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dia',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Solicitante', 'Solicitante'), ('Recepcionista', 'Recepcionista'), ('Cajero', 'Cajero')], max_length=50, null=True),
        ),
    ]
