# Generated by Django 3.1.7 on 2021-04-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0032_auto_20210408_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empleado',
        ),
    ]
