# Generated by Django 3.1.7 on 2021-04-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0035_auto_20210408_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rut_proveedor',
        ),
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Espera', 'En Espera'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='En Espera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proveedor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prooviders', to='alojamiento.proovider'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(blank=True, choices=[('A_Cocina', 'A_Cocina'), ('Cajero', 'Cajero'), ('Solicitante', 'Solicitante'), ('Recepcionista', 'Recepcionista')], max_length=50, null=True),
        ),
    ]
