# Generated by Django 3.1.7 on 2021-04-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0036_auto_20210409_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado_ticket',
            field=models.CharField(blank=True, choices=[('Activa', 'Activa'), ('Anulada', 'Anulada')], default='Activa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Espera', 'En Espera'), ('Recivida', 'Recivida'), ('Cancelada', 'Cancelada')], default='En Espera', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prooviders', to='alojamiento.proovider'),
        ),
    ]
