# Generated by Django 3.1.7 on 2021-04-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0037_auto_20210409_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_client',
            name='lista_personas',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mensaje',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
