# Generated by Django 3.1.7 on 2021-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0038_auto_20210409_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Espera', 'En Espera'), ('Recibida', 'Recibida'), ('Cancelada', 'Cancelada')], default='En Espera', max_length=50, null=True),
        ),
    ]
