# Generated by Django 3.1.7 on 2021-04-13 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamiento', '0040_auto_20210412_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proovider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proovider',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proovider',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
