# Generated by Django 3.1.7 on 2021-04-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0042_auto_20210412_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='proovider',
            name='user',
        ),
        migrations.AddField(
            model_name='proovider',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proovider',
            name='email',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proovider',
            name='empresa',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='estado_huesped',
            field=models.CharField(blank=True, choices=[('En Alojamiento', 'En Alojamiento'), ('Retirado', 'Retirado')], default='En Alojamiento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Espera', 'En Espera'), ('Recibida', 'Recibida'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='En Espera', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mensaje',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamiento.proovider'),
        ),
    ]
