# Generated by Django 3.1.7 on 2021-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0043_auto_20210415_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovider',
            name='codigo_proveedor',
            field=models.CharField(blank=True, default='#', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proovider',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proovider',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
