# Generated by Django 3.1.7 on 2021-04-17 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0047_auto_20210416_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_client',
            old_name='mensaje',
            new_name='lista_personas',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='precio_noches',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='precio_personas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='precio_servivcio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_boleta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='noches',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='personas',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_habitacion',
            field=models.CharField(blank=True, choices=[('Básico', 'Básico'), ('Plus', 'Plus'), ('Premuim', 'Premuim')], max_length=50, null=True),
        ),
    ]
