# Generated by Django 3.1.7 on 2021-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0048_auto_20210416_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_client',
            name='lista_personas',
        ),
        migrations.AddField(
            model_name='booking_client',
            name='mesnsaje',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
