# Generated by Django 3.1.7 on 2021-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0049_auto_20210417_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_client',
            old_name='mesnsaje',
            new_name='mensaje',
        ),
        migrations.AlterField(
            model_name='room',
            name='numero_habitacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
