# Generated by Django 3.1.7 on 2021-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0050_auto_20210417_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_portada',
            field=models.ImageField(default='', upload_to='fotos_portadas'),
        ),
    ]
