# Generated by Django 3.1.7 on 2021-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0051_profile_foto_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cantidad_camas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='imagen_habitacion',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_portada',
            field=models.ImageField(default='portada_default.png', upload_to='fotos_portadas'),
        ),
    ]
