# Generated by Django 3.1.7 on 2021-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0053_auto_20210421_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_client',
            name='precio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tipo_habitacion',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Compartida', 'Compartida')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_habitacion',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Compartida', 'Compartida')], max_length=50, null=True),
        ),
    ]
