# Generated by Django 3.1.7 on 2021-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0054_auto_20210421_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cantidad_personas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
