# Generated by Django 3.1.7 on 2021-04-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0055_room_cantidad_personas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='precio_noches',
            new_name='cantidad_dias',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fecha_creacion',
            new_name='hora_creacion',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='to_user',
            new_name='receptor',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='from_user',
            new_name='remitente',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='noches',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='personas',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tipo_habitacion',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cantidad_personas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='habitacion_reservada',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alojamiento.room'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='iva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='precio_dias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_boleta',
            field=models.DateField(auto_now=True),
        ),
    ]
