# Generated by Django 3.1.7 on 2021-04-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0056_auto_20210422_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subtotal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='habitacion_reservada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamiento.room'),
        ),
    ]
