# Generated by Django 3.1.7 on 2021-04-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0057_auto_20210422_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total_servicio',
        ),
    ]
