# Generated by Django 3.1.7 on 2021-04-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0058_remove_ticket_total_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cantidad_personas',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='precio_personas',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='habitacion_reservada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='alojamiento.room'),
        ),
    ]
