# Generated by Django 3.1.7 on 2021-04-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0061_auto_20210425_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo_permiso',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Solicitante', 'Solicitante'), ('Recepcionista', 'Recepcionista')], max_length=50, null=True),
        ),
    ]
