# Generated by Django 3.1.7 on 2021-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0062_profile_tipo_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_permiso',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Recepcionista', 'Recepcionista'), ('Solicitante', 'Solicitante'), ('Usuario', 'Usuario')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_boleta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
