# Generated by Django 3.1.7 on 2021-05-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0063_auto_20210504_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Cajero', 'Cajero'), ('Solicitante', 'Solicitante'), ('Recepcionista', 'Recepcionista')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Proceso', 'En Proceso'), ('Despachado', 'Despachado'), ('En Camino', 'En Camino'), ('Recibida', 'Recibida'), ('Rechazada', 'Rechazada')], default='En Proceso', max_length=50, null=True),
        ),
    ]
