# Generated by Django 3.1.7 on 2021-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0064_auto_20210507_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Cajero', 'Cajero'), ('Recepcionista', 'Recepcionista'), ('Solicitante', 'Solicitante')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_permiso',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Cajero', 'Cajero'), ('Proveedor', 'Proveedor'), ('Recepcionista', 'Recepcionista'), ('Solicitante', 'Solicitante'), ('Usuario', 'Usuario')], max_length=50, null=True),
        ),
    ]
