# Generated by Django 3.1.7 on 2021-05-08 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamiento', '0065_auto_20210508_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proovider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proovider',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='proovider',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prooviders', to='auth.user'),
        ),
    ]
