# Generated by Django 3.1.7 on 2021-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0068_auto_20210508_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='texto',
            field=models.TextField(null=True),
        ),
    ]
