# Generated by Django 3.1.7 on 2021-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0070_auto_20210516_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='categoria',
            field=models.CharField(choices=[('Ejecutivo', 'Ejecutivo'), ('Especiales', 'Especiales'), ('Generales', 'Generales')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='descripcion',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='precio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(choices=[('Sin Cargo', 'Sin Cargo'), ('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Cajero', 'Cajero'), ('Recepcionista', 'Recepcionista'), ('Solicitante', 'Solicitante')], default='Sin Cargo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rut',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='estado_huesped',
            field=models.CharField(choices=[('En Alojamiento', 'En Alojamiento'), ('Retirado', 'Retirado')], default='En Alojamiento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rut',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_permiso',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ayudante Cocina', 'Ayudante Cocina'), ('Cajero', 'Cajero'), ('Proveedor', 'Proveedor'), ('Recepcionista', 'Recepcionista'), ('Solicitante', 'Solicitante'), ('Usuario', 'Usuario')], default='Usuario', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proovider',
            name='rubro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='cantidad_camas',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='cantidad_personas',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('En Mantenimiento', 'En Mantenimiento')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='numero_habitacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='precio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tipo_habitacion',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Compartida', 'Compartida')], max_length=50, null=True),
        ),
    ]
